### PR TITLE
Updated options.js to use babel-eslint parser

### PR DESCRIPTION
**Pull request by jkingworking**
I'm using awaits and async stuff so I needed to use the babel-eslint parser. Maybe someone else will need this as well.

### CODE REVIEW

**Comment by wesleytodd** [comment]
Other than doing some digging and finding this possible issue (https://github.com/eslint/eslint/issues/6274) I think this seems like a fine change.  But it is a change away from standard.

Also, this can be solved in your project directly with this in your `package.json`:

```
  "standard": {
    "parser": "babel-eslint"
  }
```

Any thoughts from @dcousens or @JedWatson  on this?

Edit: Also hey Jonathan!! Hope things are going well on your new gig!

**Comment by jkingworking** [comment]
Hey Wes, Things are going really well. I'm obviously starting to implement a lot of what I learned from you over here.

With regards to adding this as a config in my `package.json` I tried that first but I couldn't get it to work. That's why I had to put it in the `options.js` file instead. Were you able to get that to work?

Also I thought that babel-eslint just extended eslint so it's more of an augmentation of standard than a deviation from it. But I can see why you might be reticent to use it since it's on the bleeding edge.

**Comment by wesleytodd** [comment]
Did you try using `happiness` instead of `standard` for the key?  I haven't actually used this feature, so I don't know for sure how it works.  Yes it does extend, but I would worry about it introducing bugs that are not present in standard, that was my only concern.  If neither of the other maintainers disagree then this has my vote.

And glad things are going well!

**Comment by jkingworking** [comment]
Thanks Wes. That's what I was missing, adding this to my `package.json` got it working correctly.

```
    "happiness": {
        "parser":"babel-eslint"
    }
```

**Comment by dcousens** [comment]
Great to hear @jkingworking ,  good work @wesleytodd

**Pull request closed without merging**
