### PR TITLE
updated format to version that supports tabs in jsx

### PR DESCRIPTION
**Pull request by wesleytodd**
I have a fork open on `happiness-format` that updates the esformat-jsx package to correctly support tabs.  I created this branch so that we can track that change and then publish once it is merged up.

https://github.com/martinheidegger/hapiness-format/pull/1

### CODE REVIEW

**Comment by wesleytodd** [comment]
Ok, they merged and published that module, so this is ready to go :)

**Comment by dcousens** [comment]
:+1: @wesleytodd

**Comment by wesleytodd** [comment]
Since the previous one has not been published, are we alright just lumping this in with that other release and not bumping the version again?

**Comment by dcousens** [comment]
@wesleytodd for sure.  I've SMS'd @JedWatson with no response yet.

**Comment by wesleytodd** [comment]
Awesome!  Maybe it would be a good idea to have him add you to the npm contributor list, so you can publish.  And if you are interested...ME *_wink wink *_ :)

**Comment by JedWatson** [comment]
Pushed, I'll add you both to the npm contributor list as well so this doesn't happen again.

Really sorry for missing these notifications - I have about 1k to triage and unfortunately this didn't hit my radar. To make matters worse I've been travelling (in Utah atm) with a different SIM so @dcousens's helpful sms won't actually get to me until I land back in AU :grimacing: 

FWIW if you ever want to get my attention twitter is possibly the most reliable way (I'm @jedwatson there too) and I'm always happy to get a bump if I've missed a github notification that I should have paid attention to like this one.

Thanks again @wesleytodd for all your help getting this package fixed up.

**Comment by wesleytodd** [comment]
No worries @jedwatson, totally understandable. And WOW thats a lot of notifications. Hopefully we can atleast help with that on this repo!

**Pull request merged**
